FROM strimzi/kafka:0.20.1-kafka-2.5.0
USER root:root

# RUN mkdir -p /opt/kafka/plugins/camel
# COPY deploy/camel-timer-source-kafka-connector-1.0.0-package.tar.gz /opt/kafka/plugins/camel/
# RUN tar -xvzf /opt/kafka/plugins/camel/camel-timer-source-kafka-connector-1.0.0-package.tar.gz --directory /opt/kafka/plugins/camel
# RUN rm /opt/kafka/plugins/camel/camel-timer-source-kafka-connector-1.0.0-package.tar.gz

RUN mkdir -p /opt/kafka/plugins/connect-file
COPY deploy/connect-file-3.2.2.jar /opt/kafka/plugins/connect-file

USER 1001
