# https://hub.docker.com/_/postgres
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: postgres
  name: postgres
  namespace: kafka # Change this value to match the namespace metadata.name
spec:
  containers:
    - name: postgres
      image: postgres
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_PASSWORD
          value: mysecret
      volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d
          name: localvolume
  volumes:
    - name: localvolume
      hostPath:
        path: /mnt/host-volumes/postgres
        type: DirectoryOrCreate
