---
# https://hub.docker.com/_/adminer
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: adminer
  name: adminer
  namespace: kafka
spec:
  containers:
    - name: adminer
      image: adminer
      ports:
        - containerPort: 8080
      env:
        - name: ADMINER_DEFAULT_SERVER
          value: postgres.kafka
        - name: ADMINER_DESIGN
          value: mvt
