---
apiVersion: ctlptl.dev/v1alpha1
kind: Registry
name: ctlptl-registry
port: 5005
---
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
product: kind
registry: ctlptl-registry
kindV1Alpha4Cluster:
  name: k8s-local-dev-cluster
  nodes:
    - role: control-plane
      extraMounts:
        - hostPath: ./deploy/mounts
          containerPath: /mnt/host-volumes
    - role: worker
      extraMounts:
        - hostPath: ./deploy/mounts
          containerPath: /mnt/host-volumes
